name: Publish to NPM
on:
  push:
    branches: [master]
  release:
    types: [created]

jobs:
  Release:
    name: Build, test and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install func CLI 🛠️
        run: npm install -g azure-functions-core-tools@4
      - name: Install dependencies 🛠️
        run: npm ci
      - name: Build project 👷‍♂️🏗️
        run: npm run build:all
      - name: Unit Testing 🧪
        run: npm run test:all
      - name: E2E Testing 🧪
        run: npm run e2e:all
      - name: Publish package on NPM 📦
        if: ${{ github.event_name == 'release' }}
        run: npm publish dist/packages/func --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
